#Business Analytics Industry Cluster - Fall Project: Text Analytics 
#The following results are driven by "Cognizer" 
#This R-package,developed by Collumbus Collaboratory, facilitates the use of several IBM Watson API's 
  #We are interested in 3 API's in specific
    #Alchemy Language - for sentiment analysis, keyword extraction, and emotion analysis 
    #Personality Insights - to analyze "Big 5" physcological traits, needs, and values 
    #Tone Analyzer - to emotion, language, social 

#install necssary "curl" functions from outside CRAN
  install.packages("devtools")
  install.packages("https://github.com/jeroenooms/curl/archive/master.tar.gz", repos = NULL)
  devtools::install_github("ColumbusCollaboratory/cognizer")
#install data packages used in tests
  install.packages(c("rmsfact", "testthat"))

#open/edit R Environment variables 
  r_env <- file.path(normalizePath("~"), ".Renviron")
  if (!file.exists(r_env)) file.create(r_env)
  file.edit(r_env)

#API Access Credentials
  alchemy_key <- Sys.getenv("IBM_ALCHEMY_LANGUAGE_API_KEY")
  personality_key <- Sys.getenv("PERSONALITY_USERNAME_PASSWORD") 
  tone_key <- Sys.getenv("TONE_USERNAME_PASSWORD")  

#Load Data 
trump <- readLines('/Users/Kalman/Documents/SENIOR/Business Analytics/project/Speeches/Trump_R')
#pence <- readLines('/Users/Kalman/Documents/SENIOR/Business Analytics/project/Speeches/Pence_R')
#smith <- readLines('/Users/Kalman/Documents/SENIOR/Business Analytics/project/Speeches/Smith_R')
#clinton <- readLines('/Users/Kalman/Documents/SENIOR/Business Analytics/project/Speeches/Clinton_D')
#kaine <- readLines('/Users/Kalman/Documents/SENIOR/Business Analytics/project/Speeches/Kaine_D')
#khan <- readLines('/Users/Kalman/Documents/SENIOR/Business Analytics/project/Speeches/Khan_D')

trumpData <- data.frame(trump)

#Alchemy Language 
  #1000 Free API Calls / day
  #uses "alchemy_key"



  #Sentiment Analysis - speech, sentence, word (number)
    ## List of 2
    ##  $ :List of 5
    ##   ..$ status           : chr "OK"
    ##   ..$ usage            : chr "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of U"| __truncated__
    ##   ..$ totalTransactions: chr "1"
    ##   ..$ language         : chr "english"
    ##   ..$ docSentiment     :List of 2
    ##   .. ..$ score: chr "0.736974"
    ##   .. ..$ type : chr "positive"
    ##  $ :List of 5
    ##   ..$ status           : chr "OK"
    ##   ..$ usage            : chr "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of U"| __truncated__
    ##   ..$ totalTransactions: chr "1"
    ##   ..$ language         : chr "english"
    ##   ..$ docSentiment     :List of 2
    ##   .. ..$ score: chr "0.405182"
    ##   .. ..$ type : chr "positive"

  result <- cognizer::text_sentiment(trump, alchemy_key)
  library(ggplot2)
  library(reshape2)
  sentiment = data.frame(Index=integer(),
                         Score=numeric(),
                         Type=character(),
                         stringsAsFactors=FALSE)
  for (i in 1:length(result)) {
    if (!is.null(result[[i]]$docSentiment$score)) {
      score <-result[[i]]$docSentiment$score
      type <-result[[i]]$docSentiment$type
      newRow <- data.frame(Index = i, Score = as.numeric(score) , Type = type, stringsAsFactors=FALSE)
      sentiment = rbind(sentiment,newRow)
    }
  }
  reg <-lm(Score ~ Index, data = sentiment)
  summary(reg)
  qplot(data = sentiment, x=Index, y=Score, color=Type) + geom_smooth(se=FALSE)
  
  #Linear regression of sentiments across time in speech?
    #layer trump over hillary (maybe all 6 just for this )

  #Keyword Extraction - per speech, per sentence?
    ##   ..$ status           : chr "OK" - for result$status == "OK"..
    ##   ..$ totalTransactions: chr "1" - count = count + 1
    ##   ..$ keywords         :'data.frame':    2 obs. of  2 variables:
    ##   .. ..$ relevance: chr [1:2] "0.903313" "0.878148" if relevance >= .75
    ##   .. ..$ text     : chr [1:2] "Columbus" "Ohio" - dictionary of counts => wordcloud
  
  #Emotion Analysis - over whole document, average / sentence,...
    ##   ..$ docEmotions      :List of 5
    ##   .. ..$ anger  : chr "0.070822"
    ##   .. ..$ disgust: chr "0.051115"
    ##   .. ..$ fear   : chr "0.327703"
    ##   .. ..$ joy    : chr "0.69756"
    ##   .. ..$ sadness: chr "0.150018"

#Personality Insights 
  #100 Free API Calls / month (until March 2017, then $0.02 / API call for <100,00 calls)
  #NOTE: RECOMMEND 1200+ words (pass in full speech) GET ERRORS FROM BLUEMIX (not too bad for less than 1200)
  #uses "personality_key"
  
  ##   .. .. .. .. .. .. ..$ id            : chr [1:5] "Openness" "Conscientiousness" "Extraversion" "Agreeableness" ...
  ##   .. .. .. .. .. .. ..$ name          : chr [1:5] "Openness" "Conscientiousness" "Extraversion" "Agreeableness" ...
  ##   .. .. .. .. .. .. ..$ category      : chr [1:5] "personality" "personality" "personality" "personality" ...
  ##   .. .. .. .. .. .. ..$ percentage    : num [1:5] 0.694 0.428 0.703 0.114 0.29 - output "Big Five" DEFINITIONS ON BLUEMIX & Percentages
  ##   .. .. .. .. .. .. ..$ sampling_error: num [1:5] 0.0466 0.0594 0.0453 0.0812 0.0754 - display error?
  ##   .. .. .. .. .. .. ..$ children      :List of 5
  ##   .. .. .. .. .. .. .. ..$ :'data.frame':    6 obs. of  5 variables: - NEEDS
  ##   .. .. .. .. .. .. .. .. ..$ id            : chr [1:6] "Adventurousness" "Artistic interests" "Emotionality" "Imagination" ...
  ##   .. .. .. .. .. .. .. .. ..$ name          : chr [1:6] "Adventurousness" "Artistic interests" "Emotionality" "Imagination" ...
  ##   .. .. .. .. .. .. .. .. ..$ category      : chr [1:6] "personality" "personality" "personality" "personality" ...
  ##   .. .. .. .. .. .. .. .. ..$ percentage    : num [1:6] 0.635 0.554 0.389 0.864 0.639 ...
  ##   .. .. .. .. .. .. .. .. ..$ sampling_error: num [1:6] 0.0417 0.0864 0.039 0.0535 0.0451 ...
  ##   .. .. .. .. .. .. .. ..$ :'data.frame':    6 obs. of  5 variables: - VALUES 
  ##   .. .. .. .. .. .. .. .. ..$ id            : chr [1:6] "Achievement striving" "Cautiousness" "Dutifulness" "Orderliness" ...
  ##   .. .. .. .. .. .. .. .. ..$ name          : chr [1:6] "Achievement striving" "Cautiousness" "Dutifulness" "Orderliness" ...

  #ggplot 2 extension ggradar for these
  #side by side bar charts to compare 

#Tone Analyzer 
  #1000 Free API Calls / month (then $0.0088 / API call for <250,000 calls)
  #uses "tone_key"
  
  ##   .. .. .. ..$ :'data.frame':    5 obs. of  3 variables: (EMOTION)
  ##   .. .. .. .. ..$ score    : num [1:5] 0.0708 0.0511 0.3277 0.6976 0.15
  ##   .. .. .. .. ..$ tone_id  : chr [1:5] "anger" "disgust" "fear" "joy" ...
  ##   .. .. .. .. ..$ tone_name: chr [1:5] "Anger" "Disgust" "Fear" "Joy" ...
  ##   .. .. .. ..$ :'data.frame':    3 obs. of  3 variables: (LANGUAGE)
  ##   .. .. .. .. ..$ score    : num [1:3] 0 0 0 - is this inconclusive??
  ##   .. .. .. .. ..$ tone_id  : chr [1:3] "analytical" "confident" "tentative"
  ##   .. .. .. .. ..$ tone_name: chr [1:3] "Analytical" "Confident" "Tentative"
  ##   .. .. .. ..$ :'data.frame':    5 obs. of  3 variables: (SOCIAL)
  ##   .. .. .. .. ..$ score    : num [1:5] 0.24 0.571 0.694 0.308 0.401 - What does "score" mean?
  ##   .. .. .. .. ..$ tone_id  : chr [1:5] "openness_big5" "conscientiousness_big5" "extraversion_big5" "agreeableness_big5" ...
  ##   .. .. .. .. ..$ tone_name: chr [1:5] "Openness" "Conscientiousness" "Extraversion" "Agreeableness" ...
  ##   .. .. ..$ category_id  : chr [1:3] "emotion_tone" "language_tone" "social_tone"
  ##   .. .. ..$ category_name: chr [1:3] "Emotion Tone" "Language Tone" "Social Tone"
    

#ONLY DO TRUMP AND HILLARY?
#Parse each speech by total speech, sentence, word
  #read each speech beforehand and manually correct potential error spots 
#Best way to visualize? 
  #R to process, Tableau to Visualize? 
    #R to visualize?
